// Sunday League — single file server.
// Generated by tools/build-flat.js. Edit the full project, not this file,
// unless this flat copy is all you have.

import http from 'http';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import express from 'express';
import { WebSocketServer } from 'ws';
import {
  NET, TICK_DT, FIELD, GOAL, PLAYER, STAMINA, BALL, KICK, MATCH, ROOM, TEAM, TEAM_COLORS, NAME_MAX_LENGTH, PHASE, spawnPositions, GOAL_CENTER, TARGET_GOAL, integratePlayer
} from './core.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PORT = process.env.PORT || 3000;

/* ================================================ Physics */
// Arcade physics. Pure functions, no state of its own, so it is easy to unit test.
// Everything here runs on the SERVER only - the client never simulates authoritatively.




const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);
const len = (x, y) => Math.hypot(x, y);

/** Move one player entity for dt seconds using its current input. */
function stepPlayer(p, dt) {
  integratePlayer(p, p.input, dt);
}

/** Push overlapping players apart so nobody walks through anybody. */
function resolvePlayerCollisions(players) {
  for (let i = 0; i < players.length; i++) {
    for (let j = i + 1; j < players.length; j++) {
      const a = players[i], b = players[j];
      let dx = b.x - a.x, dy = b.y - a.y;
      let d = len(dx, dy);
      const min = PLAYER.RADIUS * 2;
      if (d === 0) { dx = 0.01; dy = 0; d = 0.01; }
      if (d < min) {
        const overlap = (min - d) / 2;
        const nx = dx / d, ny = dy / d;
        a.x -= nx * overlap; a.y -= ny * overlap;
        b.x += nx * overlap; b.y += ny * overlap;
        // small elastic exchange so shoulder-to-shoulder duels feel physical
        const rel = (b.vx - a.vx) * nx + (b.vy - a.vy) * ny;
        if (rel < 0) {
          const imp = rel * 0.5;
          a.vx += nx * imp; a.vy += ny * imp;
          b.vx -= nx * imp; b.vy -= ny * imp;
        }
      }
    }
  }
}

/** Ball friction + integration + wall / post collisions. */
function stepBall(ball, dt) {
  ball.vx *= Math.pow(BALL.FRICTION, dt);
  ball.vy *= Math.pow(BALL.FRICTION, dt);
  if (len(ball.vx, ball.vy) < 6) { ball.vx = 0; ball.vy = 0; }

  const sp = len(ball.vx, ball.vy);
  if (sp > BALL.MAX_SPEED) {
    ball.vx = (ball.vx / sp) * BALL.MAX_SPEED;
    ball.vy = (ball.vy / sp) * BALL.MAX_SPEED;
  }

  ball.x += ball.vx * dt;
  ball.y += ball.vy * dt;

  const r = BALL.RADIUS;
  const mouthTop = FIELD.H / 2 - GOAL.MOUTH / 2;
  const mouthBottom = FIELD.H / 2 + GOAL.MOUTH / 2;
  const inMouth = ball.y > mouthTop && ball.y < mouthBottom;

  // Touchlines always bounce.
  if (ball.y < r)           { ball.y = r;           ball.vy = -ball.vy * BALL.WALL_BOUNCE; }
  if (ball.y > FIELD.H - r) { ball.y = FIELD.H - r; ball.vy = -ball.vy * BALL.WALL_BOUNCE; }

  // Goal lines bounce UNLESS the ball is inside the goal mouth (then it may enter).
  if (!inMouth) {
    if (ball.x < r)           { ball.x = r;           ball.vx = -ball.vx * BALL.WALL_BOUNCE; }
    if (ball.x > FIELD.W - r) { ball.x = FIELD.W - r; ball.vx = -ball.vx * BALL.WALL_BOUNCE; }
  } else {
    // inside the net: stop at the back and the side netting
    const back = GOAL.DEPTH;
    if (ball.x < -back + r)          { ball.x = -back + r;          ball.vx = -ball.vx * 0.25; }
    if (ball.x > FIELD.W + back - r) { ball.x = FIELD.W + back - r; ball.vx = -ball.vx * 0.25; }
    if (ball.x < 0 || ball.x > FIELD.W) {
      if (ball.y < mouthTop + r)    { ball.y = mouthTop + r;    ball.vy = -ball.vy * 0.3; }
      if (ball.y > mouthBottom - r) { ball.y = mouthBottom - r; ball.vy = -ball.vy * 0.3; }
    }
  }

  // Posts are solid circles at the four mouth corners.
  for (const px of [0, FIELD.W]) {
    for (const py of [mouthTop, mouthBottom]) {
      const dx = ball.x - px, dy = ball.y - py;
      const d = len(dx, dy);
      const min = r + GOAL.POST_R;
      if (d < min && d > 0) {
        const nx = dx / d, ny = dy / d;
        ball.x = px + nx * min;
        ball.y = py + ny * min;
        const dot = ball.vx * nx + ball.vy * ny;
        ball.vx = (ball.vx - 2 * dot * nx) * BALL.WALL_BOUNCE;
        ball.vy = (ball.vy - 2 * dot * ny) * BALL.WALL_BOUNCE;
        ball.hitPost = true;
      }
    }
  }
}

/** Body contact between players and the ball: dribbling and blocking. */
function resolveBallPlayerCollisions(ball, players) {
  for (const p of players) {
    const dx = ball.x - p.x, dy = ball.y - p.y;
    let d = len(dx, dy);
    const min = PLAYER.RADIUS + BALL.RADIUS;
    if (d === 0) { d = 0.01; }
    if (d < min) {
      const nx = dx / d, ny = dy / d;
      ball.x = p.x + nx * min;
      ball.y = p.y + ny * min;
      const rel = (ball.vx - p.vx) * nx + (ball.vy - p.vy) * ny;
      if (rel < 0) {
        ball.vx -= (1 + BALL.PLAYER_BOUNCE) * rel * nx;
        ball.vy -= (1 + BALL.PLAYER_BOUNCE) * rel * ny;
      }
      // running into the ball carries it forward (dribble)
      ball.vx += p.vx * PLAYER.DRIBBLE_PUSH * 0.35;
      ball.vy += p.vy * PLAYER.DRIBBLE_PUSH * 0.35;
      ball.lastTouch = p.id;
      ball.lastTouchTeam = p.team;
    }
  }
}

/**
 * Slightly bend a kick toward the target goal, but only if the shot was
 * already roughly on target. Keeps mobile playable without playing for you.
 */
function applyAimAssist(dirX, dirY, from, targetGoal) {
  const toGoalX = targetGoal.x - from.x;
  const toGoalY = targetGoal.y - from.y;
  const gl = len(toGoalX, toGoalY);
  if (gl === 0) return { x: dirX, y: dirY };
  const gx = toGoalX / gl, gy = toGoalY / gl;

  const cur = Math.atan2(dirY, dirX);
  const want = Math.atan2(gy, gx);
  let diff = want - cur;
  while (diff > Math.PI) diff -= Math.PI * 2;
  while (diff < -Math.PI) diff += Math.PI * 2;

  const CONE = 0.62, MAX = 0.30;
  if (Math.abs(diff) > CONE) return { x: dirX, y: dirY };   // way off target: no help
  const corrected = cur + clamp(diff, -MAX, MAX) * (1 - Math.abs(diff) / CONE) * 1.0;
  return { x: Math.cos(corrected), y: Math.sin(corrected) };
}

/** Returns TEAM that scored, or null. RED attacks the right goal. */
function checkGoal(ball) {
  const mouthTop = FIELD.H / 2 - GOAL.MOUTH / 2;
  const mouthBottom = FIELD.H / 2 + GOAL.MOUTH / 2;
  if (ball.y <= mouthTop || ball.y >= mouthBottom) return null;
  if (ball.x + BALL.RADIUS < 0) return TEAM.BLUE;           // ball fully over RED's line
  if (ball.x - BALL.RADIUS > FIELD.W) return TEAM.RED;
  return null;
}

// GameRoom refers to these through a namespace in the modular build.
const Physics = {
  clamp, len, stepPlayer, resolvePlayerCollisions, stepBall,
  resolveBallPlayerCollisions, applyAimAssist, checkGoal
};

/* ================================================ Protocol */
// Wire format + every piece of validation that protects the server from a bad client.


const C2S = {
  HELLO: 'hello', CREATE: 'create', JOIN: 'join', QUICK: 'quick',
  TEAM: 'team', READY: 'ready', START: 'start', LEAVE: 'leave',
  INPUT: 'input', REMATCH: 'rematch', PING: 'ping'
};

const S2C = {
  WELCOME: 'welcome', ROOM: 'room', STATE: 'state', GOAL: 'goal',
  MATCH_START: 'matchStart', MATCH_END: 'end', ERROR: 'err',
  PONG: 'pong', PEER: 'peer', KICKED: 'kicked'
};

const ERR = {
  NOT_FOUND:   { code: 'ROOM_NOT_FOUND', msg: 'Room not found. Check the code and try again.' },
  FULL:        { code: 'ROOM_FULL',      msg: 'That room is full.' },
  IN_PROGRESS: { code: 'IN_PROGRESS',    msg: 'That match has already started.' },
  NO_NAME:     { code: 'NO_NAME',        msg: 'Choose a name first.' },
  NOT_HOST:    { code: 'NOT_HOST',       msg: 'Only the host can start the match.' },
  NOT_READY:   { code: 'NOT_READY',      msg: 'Waiting for a second player.' },
  TEAM_TAKEN:  { code: 'TEAM_TAKEN',     msg: 'Your opponent already picked that side.' },
  RATE:        { code: 'RATE_LIMIT',     msg: 'Slow down.' },
  BAD:         { code: 'BAD_REQUEST',    msg: 'That request was not understood.' }
};

/** Strip anything that could break the UI or be used for injection. */
function sanitizeName(raw) {
  if (typeof raw !== 'string') return '';
  return raw
    .replace(/[<>&"'`\\]/g, '')
    .replace(/[\u0000-\u001F\u007F]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, NAME_MAX_LENGTH);
}

function sanitizeCode(raw) {
  if (typeof raw !== 'string') return '';
  const up = raw.toUpperCase().replace(/[^A-Z0-9]/g, '');
  return up.slice(0, ROOM.CODE_LENGTH);
}

const toNumber = (v) => (typeof v === 'number' && Number.isFinite(v) ? v : 0);
const clampRange = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v);

/**
 * The ONLY movement data the server ever accepts.
 * Positions, velocities, scores and goals sent by a client are ignored entirely.
 */
function validateInput(raw) {
  if (!raw || typeof raw !== 'object') return null;
  let ax = clampRange(toNumber(raw.ax), -1, 1);
  let ay = clampRange(toNumber(raw.ay), -1, 1);
  const mag = Math.hypot(ax, ay);
  if (mag > 1) { ax /= mag; ay /= mag; }
  return {
    ax, ay,
    shoot:  raw.shoot === true,
    pass:   raw.pass === true,
    sprint: raw.sprint === true,
    seq: Math.max(0, Math.min(2 ** 31, Math.floor(toNumber(raw.seq))))
  };
}

function safeParse(data) {
  try {
    if (typeof data !== 'string' || data.length > 4096) return null;
    const msg = JSON.parse(data);
    if (!msg || typeof msg !== 'object' || typeof msg.t !== 'string') return null;
    return msg;
  } catch { return null; }
}

const r1 = (n) => Math.round(n * 10) / 10;   // 1 decimal is plenty and halves packet size

/** Compact snapshot. Short keys because this goes out 30x per second. */
function buildStatePacket(room) {
  return {
    t: S2C.STATE,
    k: room.tick,
    p: room.phase,
    c: r1(room.clock),
    cd: r1(room.countdown),
    s: { R: room.score.RED, B: room.score.BLUE },
    b: { x: r1(room.ball.x), y: r1(room.ball.y), vx: r1(room.ball.vx), vy: r1(room.ball.vy) },
    e: room.entities().map((p) => ({
      i: p.id,
      x: r1(p.x), y: r1(p.y),
      vx: r1(p.vx), vy: r1(p.vy),
      f: r1(Math.atan2(p.fy, p.fx) * 100) / 100,
      t: p.team,
      st: Math.round(p.stamina),
      ch: Math.round(p.chargeRatio * 100),
      q: p.input.seq,                 // last input this player had applied
      on: p.connected ? 1 : 0
    }))
  };
}

/* ================================================ GameRoom */
// One room = one match. Fully server-authoritative: it owns positions, the ball,
// goals, the score and the clock. Clients only ever send input.





let nextEntityId = 1;

class GameRoom {
  constructor(code, onEmpty) {
    this.code = code;
    this.onEmpty = onEmpty;
    this.players = new Map();          // playerId -> player record
    this.hostId = null;
    this.phase = PHASE.LOBBY;
    this.tick = 0;
    this.clock = MATCH.DURATION;
    this.countdown = 0;
    this.score = { RED: 0, BLUE: 0 };
    this.lastScorer = null;
    this.createdAt = Date.now();
    this.lastActivity = Date.now();
    this.ball = { x: FIELD.W / 2, y: FIELD.H / 2, vx: 0, vy: 0, lastTouch: null, lastTouchTeam: null };
    this.events = [];                  // one-shot events flushed to clients each tick
  }

  // ---------------------------------------------------------------- players

  get size() { return this.players.size; }
  entities() { return [...this.players.values()]; }
  isFull() { return this.players.size >= 2; }

  freeTeam() {
    const taken = new Set(this.entities().map((p) => p.team));
    if (!taken.has(TEAM.RED)) return TEAM.RED;
    if (!taken.has(TEAM.BLUE)) return TEAM.BLUE;
    return null;
  }

  addPlayer(id, name, socketRef) {
    const team = this.freeTeam() || TEAM.RED;
    const spot = spawnPositions(team, 0);
    const p = {
      id, name, team, socket: socketRef,
      entityId: nextEntityId++,
      x: spot.x, y: spot.y, vx: 0, vy: 0, fx: team === TEAM.RED ? 1 : -1, fy: 0,
      stamina: STAMINA.MAX,
      input: { ax: 0, ay: 0, shoot: false, pass: false, sprint: false, seq: 0 },
      prevShoot: false, prevPass: false,
      chargeMs: 0, chargeRatio: 0, kickCooldown: 0,
      sprinting: false, connected: true, disconnectedAt: 0,
      inputCount: 0, inputWindow: Date.now()
    };
    this.players.set(id, p);
    if (!this.hostId) this.hostId = id;
    this.lastActivity = Date.now();
    return p;
  }

  removePlayer(id) {
    this.players.delete(id);
    if (this.hostId === id) this.hostId = this.entities()[0]?.id || null;
    if (this.players.size === 0) this.onEmpty?.(this.code);
    else if (this.phase !== PHASE.LOBBY && this.phase !== PHASE.ENDED) {
      this.phase = PHASE.ENDED;
      this.pushEvent({ t: S2C.MATCH_END, reason: 'opponent_left', score: this.score, winner: this.winner() });
    }
  }

  setTeam(id, team) {
    const p = this.players.get(id);
    if (!p || this.phase !== PHASE.LOBBY) return false;
    const taken = this.entities().some((o) => o.id !== id && o.team === team);
    if (taken) return false;
    p.team = team;
    const spot = spawnPositions(team, 0);
    p.x = spot.x; p.y = spot.y;
    return true;
  }

  markDisconnected(id) {
    const p = this.players.get(id);
    if (!p) return;
    p.connected = false;
    p.disconnectedAt = Date.now();
    p.input = { ax: 0, ay: 0, shoot: false, pass: false, sprint: false, seq: p.input.seq };
  }

  reconnect(id, socketRef) {
    const p = this.players.get(id);
    if (!p) return false;
    p.connected = true;
    p.socket = socketRef;
    p.disconnectedAt = 0;
    return true;
  }

  // ------------------------------------------------------------ match flow

  startMatch() {
    if (this.players.size < 2) return false;
    this.score = { RED: 0, BLUE: 0 };
    this.clock = MATCH.DURATION;
    this.tick = 0;
    this.resetPositions();
    this.phase = PHASE.COUNTDOWN;
    this.countdown = MATCH.KICKOFF_COUNTDOWN;
    this.pushEvent({ t: S2C.MATCH_START, duration: MATCH.DURATION });
    return true;
  }

  resetPositions() {
    let i = 0;
    for (const p of this.entities()) {
      const spot = spawnPositions(p.team, i++);
      p.x = spot.x; p.y = spot.y; p.vx = 0; p.vy = 0;
      p.stamina = STAMINA.MAX;
      p.chargeMs = 0; p.chargeRatio = 0; p.kickCooldown = 0;
      p.fx = p.team === TEAM.RED ? 1 : -1; p.fy = 0;
    }
    this.ball.x = FIELD.W / 2;
    this.ball.y = FIELD.H / 2;
    this.ball.vx = 0; this.ball.vy = 0;
    this.ball.lastTouch = null; this.ball.lastTouchTeam = null;
  }

  winner() {
    if (this.score.RED > this.score.BLUE) return TEAM.RED;
    if (this.score.BLUE > this.score.RED) return TEAM.BLUE;
    return null;
  }

  pushEvent(ev) { this.events.push(ev); }

  // ------------------------------------------------------------ simulation

  update(dt) {
    this.tick++;

    if (this.phase === PHASE.COUNTDOWN) {
      this.countdown -= dt;
      if (this.countdown <= 0) { this.countdown = 0; this.phase = PHASE.PLAYING; }
      return;
    }

    if (this.phase === PHASE.GOAL) {
      this.countdown -= dt;
      if (this.countdown <= 0) {
        this.resetPositions();
        if (this.clock <= 0) { this.endMatch(); }
        else { this.phase = PHASE.COUNTDOWN; this.countdown = MATCH.RESTART_COUNTDOWN; }
      }
      return;
    }

    if (this.phase !== PHASE.PLAYING) return;

    const list = this.entities();

    for (const p of list) {
      if (p.kickCooldown > 0) p.kickCooldown -= dt * 1000;
      this.handleKickInput(p, dt);
      Physics.stepPlayer(p, dt);
    }
    Physics.resolvePlayerCollisions(list);

    this.ball.hitPost = false;
    Physics.stepBall(this.ball, dt);
    Physics.resolveBallPlayerCollisions(this.ball, list);
    if (this.ball.hitPost) this.pushEvent({ t: 'post' });

    const scorer = Physics.checkGoal(this.ball);
    if (scorer) { this.onGoal(scorer); return; }

    this.clock -= dt;
    if (this.clock <= 0) { this.clock = 0; this.endMatch(); }
  }

  /** Charge-and-release shooting plus one-tap passing. */
  handleKickInput(p, dt) {
    const inp = p.input;

    // SHOOT: hold to charge, release to strike.
    if (inp.shoot) {
      p.chargeMs = Math.min(p.chargeMs + dt * 1000, KICK.CHARGE_MS);
      p.chargeRatio = p.chargeMs / KICK.CHARGE_MS;
    } else if (p.prevShoot) {
      const power = KICK.MIN_POWER + (KICK.MAX_POWER - KICK.MIN_POWER) * p.chargeRatio;
      this.tryKick(p, power, true);
      p.chargeMs = 0; p.chargeRatio = 0;
    }
    p.prevShoot = inp.shoot;

    // PASS: fires on the press, not the release.
    if (inp.pass && !p.prevPass) this.tryKick(p, KICK.PASS_POWER, false);
    p.prevPass = inp.pass;
  }

  tryKick(p, power, isShot) {
    if (p.kickCooldown > 0) return false;
    const dx = this.ball.x - p.x, dy = this.ball.y - p.y;
    if (Math.hypot(dx, dy) > PLAYER.KICK_RANGE + BALL.RADIUS) return false;

    // Aim where the player is facing; fall back to "toward the ball" if standing still.
    let dirX = p.fx, dirY = p.fy;
    if (Math.hypot(dirX, dirY) < 0.1) {
      const d = Math.hypot(dx, dy) || 1;
      dirX = dx / d; dirY = dy / d;
    }

    const target = TARGET_GOAL[p.team];
    const aimed = Physics.applyAimAssist(dirX, dirY, p, target);

    this.ball.vx = aimed.x * power + p.vx * 0.25;
    this.ball.vy = aimed.y * power + p.vy * 0.25;
    this.ball.x = p.x + aimed.x * (PLAYER.RADIUS + BALL.RADIUS + 2);
    this.ball.y = p.y + aimed.y * (PLAYER.RADIUS + BALL.RADIUS + 2);
    this.ball.lastTouch = p.id;
    this.ball.lastTouchTeam = p.team;
    p.kickCooldown = KICK.COOLDOWN_MS;

    this.pushEvent({ t: isShot ? 'kick' : 'pass', x: this.ball.x, y: this.ball.y, power });
    return true;
  }

  onGoal(team) {
    this.score[team]++;
    this.lastScorer = team;
    this.phase = PHASE.GOAL;
    this.countdown = MATCH.GOAL_CELEBRATION;
    const scorerName = this.entities().find((p) => p.team === team)?.name || team;
    this.pushEvent({ t: S2C.GOAL, team, score: { ...this.score }, by: scorerName });
  }

  endMatch() {
    this.phase = PHASE.ENDED;
    this.pushEvent({ t: S2C.MATCH_END, score: { ...this.score }, winner: this.winner() });
  }

  rematch(id) {
    if (this.phase !== PHASE.ENDED) return false;
    const p = this.players.get(id);
    if (!p) return false;
    p.wantsRematch = true;
    const all = this.entities();
    if (all.length >= 2 && all.every((x) => x.wantsRematch)) {
      all.forEach((x) => { x.wantsRematch = false; });
      this.startMatch();
      return true;
    }
    return false;
  }

  snapshot() { return buildStatePacket(this); }

  lobbyInfo() {
    return {
      t: S2C.ROOM,
      code: this.code,
      hostId: this.hostId,
      phase: this.phase,
      players: this.entities().map((p) => ({
        id: p.id, name: p.name, team: p.team,
        connected: p.connected, host: p.id === this.hostId,
        rematch: !!p.wantsRematch
      })),
      score: { ...this.score }
    };
  }
}

/* ================================================ RoomManager */
// Creates, finds and reaps rooms. Also runs the quick-match queue.




class RoomManager {
  constructor() {
    this.rooms = new Map();     // CODE -> GameRoom
    this.queue = [];            // playerIds waiting for a quick match
  }

  generateCode() {
    const A = ROOM.CODE_ALPHABET;
    for (let attempt = 0; attempt < 200; attempt++) {
      const bytes = crypto.randomBytes(ROOM.CODE_LENGTH);
      let code = '';
      for (let i = 0; i < ROOM.CODE_LENGTH; i++) code += A[bytes[i] % A.length];
      if (!this.rooms.has(code)) return code;     // collision check
    }
    throw new Error('Could not allocate a room code');
  }

  create() {
    const code = this.generateCode();
    const room = new GameRoom(code, (c) => this.rooms.delete(c));
    this.rooms.set(code, room);
    return room;
  }

  get(code) { return this.rooms.get(code) || null; }

  /** Find any lobby with a free slot, otherwise open a fresh one. */
  findOpenRoom() {
    for (const room of this.rooms.values()) {
      if (room.phase === 'lobby' && !room.isFull()) return room;
    }
    return this.create();
  }

  sweep(now = Date.now()) {
    for (const [code, room] of this.rooms) {
      const stale = now - room.lastActivity > ROOM.IDLE_KILL_MS;
      if (room.size === 0 || stale) this.rooms.delete(code);
    }
  }

  stats() {
    let players = 0;
    for (const r of this.rooms.values()) players += r.size;
    return { rooms: this.rooms.size, players };
  }
}

/* ================================================ GameServer */
// WebSocket front door + the single fixed-timestep loop that drives every room.






class GameServer {
  constructor(httpServer) {
    this.wss = new WebSocketServer({ server: httpServer });
    this.rooms = new RoomManager();
    this.sockets = new Map();     // sessionId -> { ws, name, roomCode }
    this.wss.on('connection', (ws) => this.onConnection(ws));
    this.startLoop();
  }

  // ------------------------------------------------------------- plumbing

  send(ws, obj) {
    if (ws && ws.readyState === 1) {
      try { ws.send(JSON.stringify(obj)); } catch { /* socket died mid-write */ }
    }
  }

  fail(ws, e) { this.send(ws, { t: S2C.ERROR, code: e.code, msg: e.msg }); }

  broadcast(room, obj) {
    const payload = JSON.stringify(obj);
    for (const p of room.entities()) {
      const s = this.sockets.get(p.id);
      if (s?.ws && s.ws.readyState === 1) { try { s.ws.send(payload); } catch {} }
    }
  }

  onConnection(ws) {
    ws.isAlive = true;
    ws.on('pong', () => { ws.isAlive = true; });
    ws.sessionId = null;
    ws.on('message', (raw) => this.onMessage(ws, raw.toString()));
    ws.on('close', () => this.onClose(ws));
    ws.on('error', () => {});
  }

  onClose(ws) {
    const id = ws.sessionId;
    if (!id) return;
    const s = this.sockets.get(id);
    if (!s) return;
    s.ws = null;
    const room = s.roomCode ? this.rooms.get(s.roomCode) : null;
    if (!room) { this.sockets.delete(id); return; }

    if (room.phase === PHASE.LOBBY || room.phase === PHASE.ENDED) {
      room.removePlayer(id);
      this.sockets.delete(id);
      if (room.size > 0) this.broadcast(room, room.lobbyInfo());
    } else {
      // Mid-match: hold the slot open so they can come back.
      room.markDisconnected(id);
      this.broadcast(room, { t: S2C.PEER, event: 'disconnected', id });
    }
  }

  // -------------------------------------------------------------- messages

  onMessage(ws, raw) {
    const msg = safeParse(raw);
    if (!msg) return this.fail(ws, ERR.BAD);

    switch (msg.t) {
      case C2S.HELLO:   return this.onHello(ws, msg);
      case C2S.PING:    return this.send(ws, { t: S2C.PONG, ts: msg.ts });
      case C2S.CREATE:  return this.onCreate(ws);
      case C2S.JOIN:    return this.onJoin(ws, msg);
      case C2S.QUICK:   return this.onQuick(ws);
      case C2S.TEAM:    return this.onTeam(ws, msg);
      case C2S.START:   return this.onStart(ws);
      case C2S.INPUT:   return this.onInput(ws, msg);
      case C2S.REMATCH: return this.onRematch(ws);
      case C2S.LEAVE:   return this.onLeave(ws);
      default:          return this.fail(ws, ERR.BAD);
    }
  }

  onHello(ws, msg) {
    const name = sanitizeName(msg.name) || 'Player';

    // Reconnect path: the client kept its session id in localStorage.
    const prior = typeof msg.sid === 'string' ? this.sockets.get(msg.sid) : null;
    if (prior && !prior.ws) {
      ws.sessionId = msg.sid;
      prior.ws = ws;
      prior.name = name;
      this.send(ws, { t: S2C.WELCOME, id: msg.sid, name, resumed: true });
      const room = prior.roomCode ? this.rooms.get(prior.roomCode) : null;
      if (room && room.reconnect(msg.sid, ws)) {
        this.send(ws, room.lobbyInfo());
        this.broadcast(room, { t: S2C.PEER, event: 'reconnected', id: msg.sid });
      }
      return;
    }

    const id = crypto.randomBytes(9).toString('base64url');
    ws.sessionId = id;
    this.sockets.set(id, { ws, name, roomCode: null });
    this.send(ws, { t: S2C.WELCOME, id, name, resumed: false });
  }

  session(ws) {
    if (!ws.sessionId) return null;
    return this.sockets.get(ws.sessionId) || null;
  }

  enterRoom(ws, room) {
    const s = this.session(ws);
    if (!s) { this.fail(ws, ERR.NO_NAME); return false; }
    if (room.isFull()) { this.fail(ws, ERR.FULL); return false; }
    if (room.phase !== PHASE.LOBBY) { this.fail(ws, ERR.IN_PROGRESS); return false; }
    s.roomCode = room.code;
    room.addPlayer(ws.sessionId, s.name, ws);
    this.broadcast(room, room.lobbyInfo());
    return true;
  }

  onCreate(ws) {
    if (!this.session(ws)) return this.fail(ws, ERR.NO_NAME);
    this.onLeave(ws, true);
    const room = this.rooms.create();
    this.enterRoom(ws, room);
  }

  onJoin(ws, msg) {
    if (!this.session(ws)) return this.fail(ws, ERR.NO_NAME);
    const code = sanitizeCode(msg.code);
    const room = this.rooms.get(code);
    if (!room) return this.fail(ws, ERR.NOT_FOUND);
    this.onLeave(ws, true);
    this.enterRoom(ws, room);
  }

  onQuick(ws) {
    if (!this.session(ws)) return this.fail(ws, ERR.NO_NAME);
    this.onLeave(ws, true);
    const room = this.rooms.findOpenRoom();
    if (this.enterRoom(ws, room) && room.isFull()) room.startMatch();
  }

  onTeam(ws, msg) {
    const room = this.roomOf(ws);
    if (!room) return;
    const team = msg.team === TEAM.RED ? TEAM.RED : msg.team === TEAM.BLUE ? TEAM.BLUE : null;
    if (!team) return this.fail(ws, ERR.BAD);
    if (!room.setTeam(ws.sessionId, team)) return this.fail(ws, ERR.TEAM_TAKEN);
    this.broadcast(room, room.lobbyInfo());
  }

  onStart(ws) {
    const room = this.roomOf(ws);
    if (!room) return;
    if (room.hostId !== ws.sessionId) return this.fail(ws, ERR.NOT_HOST);
    if (room.size < 2) return this.fail(ws, ERR.NOT_READY);
    room.startMatch();
    this.broadcast(room, room.lobbyInfo());
  }

  onRematch(ws) {
    const room = this.roomOf(ws);
    if (!room) return;
    room.rematch(ws.sessionId);
    this.broadcast(room, room.lobbyInfo());
  }

  onLeave(ws, silent = false) {
    const s = this.session(ws);
    if (!s || !s.roomCode) return;
    const room = this.rooms.get(s.roomCode);
    s.roomCode = null;
    if (!room) return;
    room.removePlayer(ws.sessionId);
    if (room.size > 0) this.broadcast(room, room.lobbyInfo());
    if (!silent) this.send(ws, { t: S2C.KICKED, reason: 'left' });
  }

  /**
   * Input is the ONLY gameplay data a client may submit.
   * Anything resembling a position, score or goal claim is discarded here.
   */
  onInput(ws, msg) {
    const room = this.roomOf(ws);
    if (!room) return;
    const p = room.players.get(ws.sessionId);
    if (!p) return;

    const now = Date.now();
    if (now - p.inputWindow > 1000) { p.inputWindow = now; p.inputCount = 0; }
    if (++p.inputCount > NET.MAX_INPUT_PER_SEC) return;   // flood guard, silently dropped

    const clean = validateInput(msg);
    if (!clean) return;
    if (clean.seq < p.input.seq) return;                  // ignore out-of-order packets
    p.input = clean;
    room.lastActivity = now;
  }

  roomOf(ws) {
    const s = this.session(ws);
    if (!s || !s.roomCode) return null;
    return this.rooms.get(s.roomCode) || null;
  }

  // ------------------------------------------------------------- main loop

  startLoop() {
    let previous = Date.now();
    let accumulator = 0;
    const step = TICK_DT * 1000;

    this.loop = setInterval(() => {
      const now = Date.now();
      accumulator += now - previous;
      previous = now;
      if (accumulator > 250) accumulator = 250;    // never spiral after a stall

      while (accumulator >= step) {
        accumulator -= step;
        this.simulate(TICK_DT, now);
      }
    }, Math.max(1, Math.floor(step / 2)));

    this.heartbeat = setInterval(() => {
      this.wss.clients.forEach((ws) => {
        if (ws.isAlive === false) return ws.terminate();
        ws.isAlive = false;
        try { ws.ping(); } catch {}
      });
      this.rooms.sweep();
    }, 15000);
  }

  simulate(dt, now) {
    for (const room of this.rooms.rooms.values()) {
      // Drop players who never came back inside the grace window.
      for (const p of room.entities()) {
        if (!p.connected && now - p.disconnectedAt > ROOM.RECONNECT_GRACE_MS) {
          room.removePlayer(p.id);
          this.sockets.delete(p.id);
          this.broadcast(room, room.lobbyInfo());
        }
      }

      const before = room.phase;
      room.update(dt);

      if (room.events.length) {
        for (const ev of room.events) this.broadcast(room, ev);
        room.events.length = 0;
      }
      if (before !== room.phase && (room.phase === PHASE.ENDED || room.phase === PHASE.LOBBY)) {
        this.broadcast(room, room.lobbyInfo());
      }
      if (room.phase !== PHASE.LOBBY) this.broadcast(room, room.snapshot());
    }
  }

  stats() { return this.rooms.stats(); }

  close() {
    clearInterval(this.loop);
    clearInterval(this.heartbeat);
    this.wss.close();
  }
}

/* ================================================ boot */

const MANIFEST = "{\n  \"name\": \"Sunday League\",\n  \"short_name\": \"Sunday League\",\n  \"description\": \"Fast 1v1 top-down football you can play in a browser with a friend.\",\n  \"start_url\": \"/\",\n  \"scope\": \"/\",\n  \"display\": \"fullscreen\",\n  \"orientation\": \"landscape\",\n  \"background_color\": \"#070d14\",\n  \"theme_color\": \"#070d14\",\n  \"icons\": [\n    { \"src\": \"/icon.svg\", \"sizes\": \"any\", \"type\": \"image/svg+xml\", \"purpose\": \"any maskable\" }\n  ]\n}";
const ICON = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 512 512\">\n  <rect width=\"512\" height=\"512\" rx=\"96\" fill=\"#070d14\"/>\n  <circle cx=\"256\" cy=\"256\" r=\"150\" fill=\"none\" stroke=\"#1e7a3e\" stroke-width=\"10\" opacity=\".9\"/>\n  <circle cx=\"256\" cy=\"256\" r=\"112\" fill=\"#f3f8f6\"/>\n  <g fill=\"#0e1a25\">\n    <path d=\"M256 168l46 33-18 55h-56l-18-55zM158 254l46-33 18 55-38 46-45-19zM354 254l-46-33-18 55 38 46 45-19zM206 356l18-46h64l18 46-50 38z\"/>\n  </g>\n</svg>";
const SERVICE_WORKER = `
const CACHE = 'sunday-league-v1';
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(['/', '/core.js'])).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => e.waitUntil(self.clients.claim()));
self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin) return;
  e.respondWith(
    fetch(e.request)
      .then((res) => { const c = res.clone(); caches.open(CACHE).then((k) => k.put(e.request, c)).catch(() => {}); return res; })
      .catch(() => caches.match(e.request).then((r) => r || caches.match('/')))
  );
});
`;

const app = express();
app.disable('x-powered-by');

app.get('/', (req, res) => res.sendFile(path.join(__dirname, 'index.html')));
app.get('/core.js', (req, res) => {
  res.type('application/javascript').sendFile(path.join(__dirname, 'core.js'));
});
app.get('/manifest.webmanifest', (req, res) => res.type('application/manifest+json').send(MANIFEST));
app.get('/icon.svg', (req, res) => res.type('image/svg+xml').send(ICON));
app.get('/sw.js', (req, res) => res.type('application/javascript').send(SERVICE_WORKER));

const httpServer = http.createServer(app);
const game = new GameServer(httpServer);

app.get('/health', (req, res) => res.json({ ok: true, ...game.stats() }));

httpServer.listen(PORT, () => {
  console.log(`\n  ⚽  Sunday League on http://localhost:${PORT}\n`);
});

for (const sig of ['SIGINT', 'SIGTERM']) {
  process.on(sig, () => { game.close(); httpServer.close(() => process.exit(0)); });
}

export { app, httpServer, game };
